### PR TITLE
Add AudioKit Sequencer test case

### PR DESCRIPTION
**Pull request by emurray2**
Looks like this may be related to the issue people are observing in AudioKit/AudioKit#2536

### CODE REVIEW

**Comment by eljeff** [comment]
In your test you try to set an event at position 4.1 but default sequence track length is 4.0.
If I understand this correctly, that's probably why you don't see an event there.

Should adding an out-of-range event automatically extend the length of the sequence? I don't generally think base code should make assumptions like that. Maybe it could print a warning?

**Comment by emurray2** [comment]
> In your test you try to set an event at position 4.1 but default sequence track length is 4.0.
> 
> If I understand this correctly, that's probably why you don't see an event there.
> 
> 
> 
> Should adding an out-of-range event automatically extend the length of the sequence? I don't generally think base code should make assumptions like that. Maybe it could print a warning?

Ah that makes sense. So the extra .1 is non-inclusive inside the loop? That makes sense why it plays beat 4.0 first too because it's hitting the last note condition in `SequencerEngine.mm` right off the bat. I agree. The print may go unnoticed too. Maybe you or I could add some notes to the documentation so people are more aware?

**Comment by eljeff** [comment]
Something ... I actually dealt with this exact same issue today and was scratching my head until I realized my lengths were not set correctly.

**Comment by emurray2** [comment]
> Something ... I actually dealt with this exact same issue today and was scratching my head until I realized my lengths were not set correctly.

For sure, it certainly caught me off guard. I thought I had found the issue above opened in AudioKit/AudioKit, but what everyone is describing there seems different. I just set the length incorrectly, but now the behavior makes sense. I'll close this for now and run some more tests, but thanks for the input 🙂! I'm still learning this sequencer code, and it helps to have someone who knows about it.

**Comment by eljeff** [comment]
I don't know about playing beat 4 if its looping, I'm just getting caught up on that issue thread.

I actually prefer if it doesn't play the next downbeat when it should be looping around to play the first downbeat. I just adjust my note lengths accordingly - simple fix, works in just about every case.

**Comment by emurray2** [comment]
> I don't know about playing beat 4 if its looping, I'm just getting caught up on that issue thread.
> 
> 
> 
> I actually prefer if it doesn't play the next downbeat when it should be looping around to play the first downbeat. I just adjust my note lengths accordingly - simple fix, works in just about every case.

Now that I think of it, that's pretty similar to what some DAWs do when you loop a track. Makes sense.

**Pull request closed without merging**
